# Generated by Django 6.0.5 on 2026-06-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="مبلغ به تومان")),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("success", "پرداخت موفق"),
                            ("failed", "پرداخت ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(blank=True, help_text="اختیاری", max_length=200),
                ),
                ("payment_gateway_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
