# Generated by Django 6.0.5 on 2026-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="crypto_amount",
            field=models.FloatField(
                blank=True, help_text="Amount in crypto to send", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="crypto_currency",
            field=models.CharField(
                blank=True,
                default="USDT",
                help_text="e.g., USDT, BTC, ETH",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_address",
            field=models.CharField(
                blank=True, help_text="Your wallet address", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(
                blank=True, help_text="Transaction hash on blockchain", max_length=200
            ),
        ),
    ]
