# Generated by Django 6.0.5 on 2026-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_transaction_confirmed_at_transaction_crypto_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="donor_email",
            field=models.CharField(
                blank=True, help_text="اختیاری - برای دریافت رسید", max_length=200
            ),
        ),
    ]
