# Generated by Django 6.0.5 on 2026-06-01 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_amount", models.BigIntegerField(help_text="هدف به تومان")),
                (
                    "collected_amount",
                    models.BigIntegerField(
                        default=0, help_text="جمع\u200cآوری شده به تومان"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, help_text="لینک عکس حیوان", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="shelters.shelter",
                    ),
                ),
            ],
        ),
    ]
